# Generated by Django 4.2.4 on 2023-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprompt',
            name='table_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprompt',
            name='user_query',
            field=models.CharField(max_length=1000),
        ),
    ]
